project_name: qlock

builds:
  - id: qlock
    binary: qlock

    goos:
      - darwin
      - windows
      - linux

    goarch:
      - amd64
      - 386

    ignore:
      - goos: darwin
        goarch: 386

    ldflags:
      - -s -w
      - -X main.version={{.Version}}

    env:
      - CGO_ENABLED=0

    hooks:
      post:
        - upx --best --ultra-brute "{{ .Path }}"

archives:
  - id: qlock
    builds: [qlock]
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"

    format_overrides:
      - goos: windows
        format: zip

release:
  name_template: "{{.Version}} Release"
  prerelease: auto

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
